### ISSUE TITLE
Server runs old version of Minecraft (v. 1.5.2)

### ISSUE THREAD

**Issue by toffer** [toffer/minecloud-ami#5]
Because of the new way Mojang distributes updated versions of the Minecraft server, the minecraft-server-manager script we rely on is not getting the latest version of Minecraft.

See issue 168 for minecraft-server-manager for details: https://github.com/marcuswhybrow/minecraft-server-manager/issues/168

**Comment by wilg** [comment]
It looks like that issue in msm (marcuswhybrow/minecraft-server-manager#168) has been closed and merged (although it may not yet be in a release?).
