### ISSUE TITLE
build-ami.py log on a t1.micro

### ISSUE THREAD

**Issue by wallyatkins** [toffer/minecloud-ami#9]
Launching instance of ami-23d9a94a...
Instance state: pending
Instance state: pending
Instance state: pending
Public DNS: ec2-174-129-151-62.compute-1.amazonaws.com
Public IP address: 174.129.151.62
Instance state: running
Instance ID: i-9ab7dbf9
Waiting 30 seconds for instance to boot...
[ec2-174-129-151-62.compute-1.amazonaws.com] Executing task 'check_instance_availability'
Waiting for cloud-init to finish running...
Waiting for cloud-init to finish running...
Waiting for cloud-init to finish running...
Instance is ready.
[ec2-174-129-151-62.compute-1.amazonaws.com] Executing task 'copy_manifests'
Copying puppet manifests...
[localhost] local: git archive --prefix=puppet-minecraft/ --output=puppet-minecraft.tar.gz HEAD
[ec2-174-129-151-62.compute-1.amazonaws.com] put: puppet-minecraft.tar.gz -> /home/ubuntu/puppet-minecraft.tar.gz
[ec2-174-129-151-62.compute-1.amazonaws.com] run: tar xzf puppet-minecraft.tar.gz
[localhost] local: rm puppet-minecraft.tar.gz
[ec2-174-129-151-62.compute-1.amazonaws.com] Executing task 'apply_manifests'
Running puppet apply...
[ec2-174-129-151-62.compute-1.amazonaws.com] sudo: puppet apply -v --modulepath=/home/ubuntu/puppet-minecraft/modules /home/ubuntu/puppet-minecraft/manifests/base.pp
[ec2-174-129-151-62.compute-1.amazonaws.com] out: info: Applying configuration version '1374717354'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Exec[apt-update]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Exec[hold_grub]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Exec[apt-upgrade]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Package[tree]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Package[zip]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[first]/Apt/Package[libpq-dev]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/Package[python-dev]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/Package[python-setuptools]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/Exec[easy_install pip]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Oracle_java/User[oab]/ensure: created
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Oracle_java/Exec[git_clone_oab]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Oracle_java/Exec[build_java]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Oracle_java/Package[oracle-java7-jre]/ensure: ensure changed 'purged' to 'present'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/Package[virtualenv]/ensure: created
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/Exec[install-virtualenv]/returns: executed successfully
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[second]/Virtualenv/File[/usr/local/venv/requirements.txt]/ensure: defined content as '{md5}1c58a1ef9b23ac010406f7f2167a5b9c'
[ec2-174-129-151-62.compute-1.amazonaws.com] out: err: /Stage[second]/Virtualenv/Exec[pip-install-requirements]/returns: change from notrun to 0 failed: /usr/local/venv/bin/pip install -r /usr/local/venv/requirements.txt returned 1 instead of one of [0] at /home/ubuntu/puppet-minecraft/modules/virtualenv/manifests/init.pp:43
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-s3-sync]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-s3-sync]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/usr/local/bin]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/usr/local/bin]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-backup-archives-to-s3.sh]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-backup-archives-to-s3.sh]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-update-instance-state]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-update-instance-state]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/pip-2.7]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/pip-2.7]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-update-auth-lists.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-update-auth-lists.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-update-instance-state.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-update-instance-state.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-manage-restore-working-files-from-s3.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-manage-restore-working-files-from-s3.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/virtualenv]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/virtualenv]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/pip]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/pip]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-update-auth-lists]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-update-auth-lists]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-update-auth-lists remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-update-auth-lists remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-pre-shutdown-backup.sh]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-pre-shutdown-backup.sh]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-update-auth-lists defaults 96 04]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-update-auth-lists defaults 96 04]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/virtualenv-2.7]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/virtualenv-2.7]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-manage-pre-shutdown-backup.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-manage-pre-shutdown-backup.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-redis-listener.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-redis-listener.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-update-download-url.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-update-download-url.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/supervisor]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/supervisor]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-update-instance-state remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-update-instance-state remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-update-instance-state defaults 98 06]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-update-instance-state defaults 98 06]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-jar-update]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-jar-update]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-jar-update remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-jar-update remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-jar-update defaults 96 04]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-jar-update defaults 96 04]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-track-active-players.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-track-active-players.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/cron.d]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/cron.d]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/etc/cron.d/.placeholder]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/etc/cron.d/.placeholder]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/etc/cron.d/msm-backup-working-files-to-s3]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/etc/cron.d/msm-backup-working-files-to-s3]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/etc/cron.d/msm-track-active-players]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/etc/cron.d/msm-track-active-players]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Group[minecraft]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Group[minecraft]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/User[minecraft]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/User[minecraft]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/dev/shm/msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/dev/shm/msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[git_clone_msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[git_clone_msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/etc/init.d/msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/etc/init.d/msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[update-rc.d -f msm remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[update-rc.d -f msm remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/etc/msm.conf]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/etc/msm.conf]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[msm_update]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[msm_update]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[update-rc.d msm defaults 97 03]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[update-rc.d msm defaults 97 03]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[msm_jargroup_create]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[msm_jargroup_create]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[msm_server_create]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[msm_server_create]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/servers/default/active]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/servers/default/active]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Exec[msm_jar]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Exec[msm_jar]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/servers/default/worldstorage/world]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/servers/default/worldstorage/world]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/servers/default/world]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/servers/default/world]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/archives]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/archives]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/archives/logs]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/archives/logs]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/archives/worlds]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/archives/worlds]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/archives/backups]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/archives/backups]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-s3-sync remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-s3-sync remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-s3-sync defaults 95 05]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-s3-sync defaults 95 05]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/opt/msm/servers/default/server.properties]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/opt/msm/servers/default/server.properties]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/Service[msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/Service[msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-backup-working-files-to-s3.py]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-backup-working-files-to-s3.py]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /File[/usr/local/bin/msm-restore-working-files-from-s3.sh]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /File[/usr/local/bin/msm-restore-working-files-from-s3.sh]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm/File[/usr/local/bin/msm]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm/File[/usr/local/bin/msm]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-log-rotate]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/init.d/msm-log-rotate]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-log-rotate remove]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d -f msm-log-rotate remove]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-log-rotate defaults 96 04]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Exec[update-rc.d msm-log-rotate defaults 96 04]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Package[supervisor]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Package[supervisor]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/File[/etc/supervisor/conf.d/msm-redis-listener.conf]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/File[/etc/supervisor/conf.d/msm-redis-listener.conf]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: /Stage[main]/Msm_backup_restore/Service[supervisor]: Dependency Exec[pip-install-requirements] has failures: true
[ec2-174-129-151-62.compute-1.amazonaws.com] out: warning: /Stage[main]/Msm_backup_restore/Service[supervisor]: Skipping because of failed dependencies
[ec2-174-129-151-62.compute-1.amazonaws.com] out: info: Creating state file /var/lib/puppet/state/state.yaml
[ec2-174-129-151-62.compute-1.amazonaws.com] out: notice: Finished catalog run in 254.11 seconds
[ec2-174-129-151-62.compute-1.amazonaws.com] out: 

Disconnecting from ec2-174-129-151-62.compute-1.amazonaws.com... done.
[localhost] local: git rev-parse --verify --short HEAD
Building AMI...
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI state: pending
AMI is ready.
AMI ID: ami-49017a20
AMI Name: Minecraft-Server-001
AMI Description: Built on 2013-07-24 from cbccb8b
Terminating instance...
Instance state: shutting-down
Instance state: shutting-down
Instance terminated.

**Comment by toffer** [comment]
Thanks for the report.

This is the same issue as: https://github.com/toffer/minecloud-ami/issues/8.
